### ISSUE TITLE
Does not handle lvar-injecting match properly

### ISSUE THREAD

**Issue by whitequark** [seattlerb/ruby_parser#120]
Demonstrated by:

```
[1] pry(main)> def f; if /(?<foo>bar)/ =~ 'bar' && p(foo); foo; end; end; f
"bar"
=> "bar"
```

```
$ ruby_parse foo.rb 
# file = foo.rb loc = 1
s(:if,
 s(:and,
  s(:match2, s(:lit, /(?<foo>bar)/), s(:str, "bar")),
  s(:call, nil, :p, s(:call, nil, :foo))),
 s(:call, nil, :foo),
 nil)
```

Expected result: both occurences of `s(:call, nil, :foo)` are replaced with `s(:lvar, :foo)`.

I am myself baffled as to implementing this, because AFAIK lvar-injecting match must happen in conditional context, but at the point where `p(foo)` occurs the `if` was not reduced yet, and so the context is unknown. However, Ruby has already marked `foo` as lvar.

**Comment by zenspider** [comment]
Converted into a failing test. Closing.
