### ISSUE TITLE
Incorrect handling of nesting for special nodes in conditional context

### ISSUE THREAD

**Issue by whitequark** [seattlerb/ruby_parser#121]
Demonstrated by:

(correct case)

```
$ cat >foo.rb
if /a/ && /b/; end
$ ruby_parse foo.rb 
# file = foo.rb loc = 1
s(:if, s(:and, s(:match, s(:lit, /a/)), s(:match, s(:lit, /b/))), nil, nil)
```

(incorrect case)

```
$ cat >foo.rb
if (/a/../b/)../c/; end
$ ruby_parse foo.rb 
# file = foo.rb loc = 1
s(:if, s(:flip2, s(:dot2, s(:lit, /a/), s(:lit, /b/)), s(:lit, /c/)), nil, nil)
```

In the latter:
- All `s(:lit)` nodes should've been wrapped in `s(:match)` nodes,
- The inner `s(:dot2)` node should've been `s(:flip2)`.

Producing a sane behavior example for this is surprisingly hard, but running the incorrect case with `-w` will produce three `warning: regex literal in condition` messages, which gives an idea of how it's parsed.

**Comment by zenspider** [comment]
Converted into a failing test. Closing.
