### ISSUE TITLE
Ignore everything after \r in heredoc marker in <= 2.0

### ISSUE THREAD

**Issue by whitequark** [seattlerb/ruby_parser#162]
The following code: `"<<E\nfoo\nE\rO"`, represented as a Ruby string, is parsed fine in 2.0 and below (it evaluates to `"foo\n"`, but is an unterminated string in >= 2.1.

Note that the fix is _not_ backported (nor will be) into 2.0 and below.

**Comment by zenspider** [comment]
Converted into a failing test. Closing.
