### ISSUE TITLE
Newline character within string counted as a new line

### ISSUE THREAD

**Issue by JacobNinja** [seattlerb/ruby_parser#171]
``` ruby
def test_string_newline_bug
  rb = <<-RUBY
class Test
  def foo
    "test\n"
  end
  def bar
  end
end
  RUBY
  pt = s(:class, :Test, nil, s(:defn, :foo, s(:args), s(:str, "test\n")), s(:defn, :bar, s(:args), s(:nil)))
  assert_parse_line rb, pt, 1
  assert_equal 5, result.last.line
end
```

Expected: `bar` is defined on line `5`
Actual: `bar` is defined on line 6

I've identified the source of the bug here: https://github.com/seattlerb/ruby_parser/blob/master/lib/ruby_parser_extras.rb#L837

**Comment by zenspider** [comment]
I've got this in the form of a failing test now... but I'm not sure of a fix yet. :(

**Comment by zenspider** [comment]
AFAICT, this has been fixed for several years.
