### ISSUE TITLE
parse error on value ":" (tCOLON)

### ISSUE THREAD

**Issue by 2called-chaos** [seattlerb/ruby_parser#172]
I hope I'm right that this is ruby_parser related (I have this issue with brakeman but other similar issues were redirected here).

I have a Rails 4 application with the new hash syntax everywhere. Two files however failed to parse:

<hr>

/Volumes/code/_bmonkeys/tomatic/app/views/backend/orders/show.html.erb:7 :: parse error on value ":" (tCOLON) Could not parse
```erb
6: <% if order._.payment_status == "new" %>
7:   <%= link_to icon(:ban, "terminate"), terminate_backend_order_path(order), class: "btn btn-danger btn-xs", data: { confirm: "The user will lose it's cart, proceed?" } %>
8: <% else %>
```

/Volumes/code/_bmonkeys/tomatic/app/views/layouts/application.html.erb:11 :: parse error on value ":" (tCOLON)  Could not parse
```erb
10: <link rel="icon" href="<%= image_url "gp_mini.png" %>" type="image/png">
11: <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
12: <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic" rel="stylesheet" type="text/css">
```

<hr>

Any ideas whether this is my fault or the parser is having troubles?

Cheers,

Sven

**Comment by zenspider** [comment]
Closing.
