### ISSUE TITLE
Should parse quoted symbols :'a' and keys {'a':1} on 2.2

### ISSUE THREAD

**Issue by whitequark** [seattlerb/ruby_parser#175]
See also upstream commit ruby/ruby@cbdac1ea.

**Comment by mattyb** [comment]
+1

example:
```
COUNTRIES = { 'USA': :us,
              'Canada': :ca }
```

error (via brakeman)
```
Odd number (2) list for Hash. s(:array, s(:str, "USA"))
```

**Comment by arturopie** [comment]
I also get this error. This is how to reproduce:

```
RubyParser.new.parse "{ 'a': :b }"
```

It raises the following error:

```
RubyParser::SyntaxError: Odd number (2) list for Hash. s(:array, s(:str, "a"))
```

**Comment by doits** [comment]
Getting `Racc::ParseError` with:

```
RubyParser.new.parse "puts 'bla': {}"
--> Racc::ParseError: (string):1 :: parse error on value ":" (tCOLON)
```

Of course writing it like this is bad style (it is shorter to simply write `bla: {}`), but it is still valid ruby syntax.

**Comment by arturopie** [comment]
@doits You are right, and sometimes you can not write it that way. For example, when the key have special characters.

For example, `{ bla/bla: {} }` is invalid ruby and the only way to write it is ` { 'bla/bla': {} }`

That's why I think this issue is important.

**Comment by doits** [comment]
@arturopie sure, only in my example it is not mandatory and I didn't explicitly say it is not always not mandatory (but I see one could read this into it) ;-)

What I meant to say: I think this issue should be fixed, too.

**Comment by backus** [comment]
+1 Breaks flog for us.

**Comment by Onumis** [comment]
+1 also want to see this fixed as [RubyCritic](https://github.com/whitesmith/rubycritic) relies on it.

**Comment by presidentbeef** [comment]
This was fixed a while ago.
