### ISSUE TITLE
Regular expression breaks file parsing

### ISSUE THREAD

**Issue by liamdawson** [seattlerb/ruby_parser#182]
ruby_parser 3.6.5

In one particular ruby file, I have the following two lines:

    has_many :security_questions, autosave: false
    EMAIL_REGEX = /^([a-zA-Z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?)$/i

Running `RubyParser#parse` over that file (via brakeman) causes an error to occur on line one (`parse error on value ":" (tCOLON)`). Commenting out line 2 stops the error from occurring.

I was able to replicate it via:

    irb(main):002:0> RubyParser.new.parse "call_something a: :b
    irb(main):003:0" EMAIL_REGEX = /^([a-zA-Z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?)$/i"

which results in

    Racc::ParseError: (string):1 :: parse error on value ":" (tCOLON)

**Comment by zenspider** [comment]
minimal repro:

```ruby
/#$%/i
```

workaround: don't put # and $ together for now.

**Comment by liamdawson** [comment]
Can confirm the workaround works for now.

**Comment by zenspider** [comment]
Fixed.
