### ISSUE TITLE
Equivalent lambda and stabby lambda should parse into the same expression

### ISSUE THREAD

**Issue by jaredbeck** [seattlerb/ruby_parser#186]
Given **one argument**, lambda and stabby lambda parse into the same expression, as expected.

```ruby
RubyParser.new.parse("lambda { |x| :x }")
=> s(:iter, s(:call, nil, :lambda), s(:args, :x), s(:lit, :x))
RubyParser.new.parse("->(x) { :x }")
=> s(:iter, s(:call, nil, :lambda), s(:args, :x), s(:lit, :x))
```

However, with **zero arguments**, they do **not** parse the same.

```ruby
RubyParser.new.parse("-> { :x }")
=> s(:iter, s(:call, nil, :lambda), 0, s(:lit, :x))
RubyParser.new.parse("lambda { :x }")
=> s(:iter, s(:call, nil, :lambda), s(:args), s(:lit, :x))
```

I'm using version 3.6.6.

**Comment by zenspider** [comment]
This is true, and (was) intentional:

```
 % irb18
>> lambda { :x }.call 42
=> :x
>> proc { :x }.call 42
=> :x
```

nowadays:

```
>> -> { :x }.call 42
ArgumentError: wrong number of arguments (1 for 0)
	from (irb):1:in `block in irb_binding'
	from (irb):1:in `call'
	from (irb):1
	from /usr/bin/irb:12:in `<main>'
>> lambda { :x }.call 42
ArgumentError: wrong number of arguments (1 for 0)
	from (irb):2:in `block in irb_binding'
	from (irb):2:in `call'
	from (irb):2
	from /usr/bin/irb:12:in `<main>'
>> proc { :x }.call 42
=> :x
>> Proc.new { :x }.call 42
=> :x
```

so it should probably formulate args based on the name... tho it can also just leave it up to whatever runtime is processing. It shouldn't make a difference.

**Comment by jaredbeck** [comment]
Thanks for the super-quick response.  That's interesting; I didn't know about that change to lambda in 1.9, or the fact that procs (still) don't care about arity.

> so it should probably formulate args based on the name

Do you mean that, because stabby lambda is parsed as `:lambda`, i.e. the same "name", that it should also parse as `s(:args)`?  I agree, for consistency.

> tho it can also just leave it up to whatever runtime is processing. It shouldn't make a difference.

While it's true that processors can handle both cases (ruby2ruby does) it would be simpler for the processor if the expressions were consistent.

Finally, switching to `s(:args)` would produce better output in ruby2ruby.

```ruby
Ruby2Ruby.new.process(s(:iter, s(:call, nil, :lambda), 0, s(:lit, :x)))
=> "lambda { || :x }" # this is confusing, looks like logical disjunction
Ruby2Ruby.new.process(s(:iter, s(:call, nil, :lambda), s(:args), s(:lit, :x)))
=> "lambda { :x }" # common code style
```

**Comment by jaredbeck** [comment]
By the way, if you are interested in this change, I'd love to take a crack at a PR.  I think parsers are the coolest :)

**Comment by zenspider** [comment]
Go for it.

**Comment by jaredbeck** [comment]
Thanks!  Closing, as this issue is now represented by PR https://github.com/seattlerb/ruby_parser/pull/189
