### ISSUE TITLE
Should not emit backslashes in regexp AST nodes under certain conditions

### ISSUE THREAD

**Issue by whitequark** [seattlerb/ruby_parser#190]
E.g. (assuming the regexp AST is meant to represent whatever `/literal/.source` returns, which it probably should):

```
[2] pry(main)> Ruby19Parser.new.parse(%{%r'\\''})
=> s(:lit, /\'/)
[3] pry(main)> %r'\\''
SyntaxError: unexpected tSTRING_BEG, expecting end-of-input
[3] pry(main)> %r'\''
=> /'/
```

The actual semantics is somewhat contrived, see https://github.com/whitequark/parser/issues/192#issuecomment-96404575 for details.

**Comment by zenspider** [comment]
Converted into a failing test. Closing.
