### ISSUE TITLE
[Bug 11107] "p ->() do a(1) do end end" causes an error

### ISSUE THREAD

**Issue by whitequark** [seattlerb/ruby_parser#192]
See https://bugs.ruby-lang.org/issues/11107. Note the backports to 2.0/2.1.

**Comment by whitequark** [comment]
Also this https://github.com/whitequark/parser/commit/fc2107386b90170963e94b1b4c7e10863c8ce010

**Comment by haggen** [comment]
Any news on this since Apr 2015?

**Comment by zenspider** [comment]
Fixed. Thank you.
