### ISSUE TITLE
The double-underscore __FILE__ keyword

### ISSUE THREAD

**Issue by jaredbeck** [seattlerb/ruby_parser#194]
The double-underscore [`__FILE__`][1] keyword parses into a `s(:str)`.  Is this the expected behavior?

```
RubyParser.new.parse("__FILE__") #=> s(:str, "(string)")
```

I'm using version 3.7.0.

[1]: https://github.com/ruby/ruby/blob/trunk/doc/keywords.rdoc

**Comment by zenspider** [comment]
It's what `__FILE__` is, a string representing the current file.

From MRI's `parse.y`:

```c
      case keyword__FILE__:
        return NEW_STR(rb_str_dup(ruby_sourcefile_string));
```

**Comment by jaredbeck** [comment]
> It's what __FILE__ is, a string representing the current file.

Converting to a string makes sense, but the file that contained the `__FILE__` keyword was not named `(string).rb`.

**Comment by zenspider** [comment]
That's on you: https://github.com/seattlerb/ruby_parser/blob/master/lib/ruby_parser_extras.rb#L1023

**Comment by jaredbeck** [comment]
Well, is it even possible?  I mean, the input to `RubyParser#parse` is a string, the contents of a file, not the path to the file.  

Given that it's not possible, wouldn't it be better to represent the `__FILE__` keyword as a new `sexp_type`, e.g. `s(:kw_file)` to pick the first name that comes to mind.

**Comment by jaredbeck** [comment]
Thanks for the explanation.  Closing.
