### ISSUE TITLE
Ruby22Parser: new_call() being called without args

### ISSUE THREAD

**Issue by mzazrivec** [seattlerb/ruby_parser#198]
With Ruby22Parser:

```ruby
class RubyXXParser < Ruby22Parser
  def new_call(*args)
    p args
    super *args
  end
end
```

```ruby
> RubyXXParser.new.parse "x._('foo')"
[nil, :x]
[s(:call, nil, :x), :_, s(:array, s(:str, "foo"))]
=> s(:call, s(:call, nil, :x), :_, s(:str, "foo"))

> RubyXXParser.new.parse "_('foo')"
[nil, :_]
=> s(:call, nil, :_, s(:str, "foo"))
```

While when we try the same thing with Ruby19Parser:

```ruby
class RubyYYParser < Ruby19Parser
  def new_call(*args)
    p args
    super *args
  end
end
```

we can see the following new_call invocations:

```ruby
> RubyYYParser.new.parse "x._('foo')"
[nil, :x]
[s(:call, nil, :x), :_, s(:array, s(:str, "foo"))]
=> s(:call, s(:call, nil, :x), :_, s(:str, "foo"))

> RubyYYParser.new.parse "_('foo')"
[nil, :_, s(:array, s(:str, "foo"))]
=> s(:call, nil, :_, s(:str, "foo"))
```

Interestingly enough, the resulting s-expression is the same in both scenarios, it's just
the invocation of new_call() routine that differs here.

Other gems, namely `gettext_i18n_rails` rely on `new_call()` -- the gem overrides new_call
with its own version, where it tries to detect invocations of gettext routines in ruby / haml
source files (all to create gettext translation catalogs).

Obviously, the `new_call` routine from gettext_i18n_rails needs to see content of
the gettext function, to be able to extract the translation strings. This used to work with
Ruby19Parser, but seems to be broken with Ruby20Parser.

Where do we go from here?

**Comment by presidentbeef** [comment]
Just throwing this out there, but if the first two arguments are consistent, why not just define it the same way it is [here](https://github.com/seattlerb/ruby_parser/blob/59226ed9b918d80476b35cbc4a7bcb6fcdc61921/lib/ruby_parser_extras.rb#L560) in ruby_parser? 

```ruby
class RubyYYParser < Ruby22Parser
  def new_call recv, meth, args = nil
    super
  end
end
```

or to future-proof even more

```ruby
class RubyYYParser < Ruby22Parser
  def new_call recv, meth, *args
    super
  end
end
```

**Comment by martinpovolny** [comment]
@presidentbeef : in the `gettext_i18n_rails` it is defined the same way as you suggest. Here: https://github.com/grosser/gettext_i18n_rails/blob/master/lib/gettext_i18n_rails/ruby_gettext_extractor.rb#L102

The example above is just a minimal reproducer for the bug.

**Comment by mzazrivec** [comment]
@presidentbeef Yes, though that's not quite the point of this report.

What I meant to report here was the fact that with Ruby22Parser being used in
`gettext_i18n_rails` gem, we're not able to parse gettext strings out of our sources
(haml files for example), because the `new_call` routine never gets the *args argument
filled with the values as it used to with Ruby19Parser.

**Comment by presidentbeef** [comment]
Ah, sorry. I misunderstood. I thought the extra args were the problem, not the lack of them.

**Comment by zenspider** [comment]
Should I point out that `new_call` is not documented, so it isn't considered public API and I am allowed to change its use as I see fit? In this case, the 2.2 grammar refactored some productions so `new_call` is used differently and then amended with args. It isn't there as a place to hook.

What are you actually trying to do?

**Comment by martinpovolny** [comment]
@zenspider : we are trying to fix the https://github.com/grosser/gettext_i18n_rails to work with ruby 2.2 on our project https://github.com/ManageIQ/manageiq. 

My conclusion at this point is that we have to fix the gem to walk the parsed tree instead of relying on the `new_call` to behave the same as it did previously. As you pointed out and as @matthewd hinted.

**Comment by zenspider** [comment]
Hey! ManageIQ... I'm familiar with that project. :P

https://github.com/grosser/gettext_i18n_rails/blob/master/lib/gettext_i18n_rails/ruby_gettext_extractor.rb#L102-L136

yeah. this is absolutely wrong. The code should be a `SexpProcessor` subclass with a `process_call` method and it would be incredibly simple to write and would (pretty much?) never break even if ruby_parser internals change.

**Comment by zenspider** [comment]
That said, I have changes to change the way the generated ruby2x parsers deal with fcall by having it pass up just the message name. Either way, it is WRONG what that gem is doing.

**Comment by zenspider** [comment]
```diff
diff -r old/lib/ruby_parser.yy new/lib/ruby_parser.yy
--- old/lib/ruby_parser.yy
+++ new/lib/ruby_parser.yy
@@ -290,21 +290,21 @@
                     }
 
            fcall: operation
-                    {
-                      result = new_call nil, val[0].to_sym
-                    }
 
          command: fcall command_args =tLOWEST
                     {
-                      result = val[0].concat val[1][1..-1] # REFACTOR pattern
+                      msg, args = val
+                      result = new_call nil, msg.to_sym, args
                     }
                 | fcall command_args cmd_brace_block
                     {
-                      result = val[0].concat val[1][1..-1]
-                      if val[2] then
-                        block_dup_check result, val[2]
+                      call, args, block = val
+                      result = new_call nil, call.to_sym, args
+
+                      if block then
+                        block_dup_check result, block
 
-                        result, operation = val[2], result
+                        result, operation = block, result
                         result.insert 1, operation
                       end
                     }
@@ -962,7 +962,8 @@
                 | backref
                 | tFID
                     {
-                      result = new_call nil, val[0].to_sym
+                      msg, = val
+                      result = new_call nil, msg.to_sym
                     }
                 | kBEGIN
                     {
@@ -1043,8 +1044,10 @@
                     }
                 | fcall brace_block
                     {
-                      oper, iter = val[0], val[1]
-                      call = oper # FIX
+                      msg, iter = val
+
+                      call = new_call nil, msg.to_sym
+
                       iter.insert 1, call
                       result = iter
                       call.line = iter.line
@@ -1567,8 +1570,11 @@
                     }
                     paren_args
                     {
-                      args = self.call_args val[2..-1]
-                      result = val[0].concat args[1..-1]
+                      msg, lineno, args = val
+
+                      args = self.call_args [args]
+                      result = new_call nil, msg.to_sym, args
+                      result.lineno = lineno
                     }
                 | primary_value tDOT operation2 opt_paren_args
                     {
```

**Comment by martinpovolny** [comment]
@zenspider : ok, so let's fix the gettext_i18n_rails gem using `SexpProcessor`.

Just one question: is there a way to get the `lineno` as seen here: `https://github.com/grosser/gettext_i18n_rails/blob/master/lib/gettext_i18n_rails/ruby_gettext_extractor.rb#L122`
when using the SexpParser? 

Thx!

**Comment by presidentbeef** [comment]
You should be able to use `Sexp#line`.

**Comment by zenspider** [comment]
Yup yup. What @presidentbeef said. All sexps have `#file` and `#line`.

**Comment by martinpovolny** [comment]
So we shall close this as not-a-bug. Thx!

**Comment by zenspider** [comment]
> On Oct 6, 2015, at 11:25, Martin Povolny <notifications@github.com> wrote:
> 
> So we shall close this as not-a-bug. Thx!

Let me know if you need any assistance on the other side of this. I have bad history w/ grosser but I can try to provide objective advice.
