### ISSUE TITLE
Chinese is not allowed as a global variable

### ISSUE THREAD

**Issue by 331299** [seattlerb/ruby_parser#202]
If I use a Chinese global variable, it will throw an error "$\u8BED" is not allowed as a global variable name.
Then I hacked ruby_lexer.rex.rb, like this "text = ss.scan(/\$[\u4e00-\u9fa5\w]+|\$\w+/)"

**Comment by zenspider** [comment]
Not knowing Chinese, I can't work with this. Please provide a reproduction.

**Comment by 331299** [comment]
for example $测试 = 1

**Comment by zenspider** [comment]
Fixed. Thank you.
