### ISSUE TITLE
Ruby 2.3.0 not yet supported

### ISSUE THREAD

**Issue by miketheman** [seattlerb/ruby_parser#205]
Ruby 2.3.0 was released on Dec 25, 2015. https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/

Running a tool that relies on ruby_parser raises:

> /Users/miketheman/.rvm/gems/ruby-2.3.0/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1393:in `for_current_ruby': unrecognized RUBY_VERSION 2.3.0 (RuntimeError)

I thought I would take a stab at adding the version to the code, and running some tests, but there's no apparent "getting started" on the repo - so I wasn't sure what versions of dependencies to install.

I did this, so far:

```shell
$ gem install hoe
$ rake check_extra_deps
$ rake install_plugins
$ rake test
[1/6] Isolating sexp_processor (~> 4.1).
...
<lot of test output>
3646 runs, 17835 assertions, 15 failures, 0 errors, 16 skips
```
There's a dependency on the `minitest` gem that isn't reflected anywhere.

The failures seem to have been introduced in 4431d1859b1249ab5128d85070efd7738b1ac2e6 - checking out immediately prior (73a30979afdd7b3b64263d7d771b20715222878f) passes tests.

I'm happy to try and help out, but I'm not certain how to get started here.

**Comment by jbodah** [comment]
+1 any documentation on compiling the parser files would be helpful for noobs like me :smile_cat:

**Comment by presidentbeef** [comment]
To get started: `gem install hoe minitest && rake newb`

After that, just running `rake` will compile the parser and run the tests. `rake clean` to wipe all the generated files, and `rake gem` to build the gem in `pkg/`.

**Comment by zenspider** [comment]
There is support for 2.3 in ruby_parser now. It's about to be released. Please close if the next release meets your needs.

**Comment by miketheman** [comment]
@zenspider thanks so much for the update! I can't find any release tags in this repo - how might I discover which release da22d1e256305dff2bb549e9f13fcf9f69c43bb2 makes it into?

**Comment by lienvdsteen** [comment]
+1

**Comment by loed-idzinga** [comment]
Is there a version released for this issue?

**Comment by todd** [comment]
I've been tracking RubyGems for the last two weeks and haven't seen a release yet. Is there anything we can do to get a new version cut and released ASAP? Is there anything any of us can do to help?

**Comment by Onumis** [comment]
@loed-idzinga @todd It's been released: https://github.com/seattlerb/ruby_parser/commit/a966b2b7cf62567a34292561b7f00606e590a3bc

This can be closed now.

**Comment by loed-idzinga** [comment]
@Onumis Yeah, can confirm my problem has been resolved. Many thanks! :)

**Comment by gkop** [comment]
I'm trying to figure out what's going wrong when I call `ruby_parse` on this input and get the dreaded `#<Racc::ParseError: bar.rb:3 :: parse error on value ":" (tCOLON)> for bar.rb`:

```ruby
# in bar.rb
class Bar
  def frobulate
    foo(baz: true)

    burp = herp&.derp
  end
end
```

I can make another simple case that results in `#<Racc::ParseError: foo.rb:3 :: parse error on value "&." (error)>`:

```ruby
# in foo.rb
class Foo
  def frobulate
    bar = baz&.to_s
  end
end
```

Using Ruby 2.3.0 and ruby_parser 3.8.1

I set out to make a failing test case for ruby_parser. Thanks @miketheman and @presidentbeef for the instructions upthread. I got stuck on `rake newb`, [output here](https://gist.github.com/gkop/d460c94706117a094709)

**Comment by zenspider** [comment]
Please file a separate issue.

**Comment by gkop** [comment]
Thanks for the quick reply @zenspider . Would #201 be an acceptable existing issue to hop on? It's a rather mysterious issue but the subject line seems spot on. It's unclear to me the relationship between ruby_parser and https://github.com/whitequark/parser (I couldn't find a ruby_parser.gemspec file anywhere :/ )

**Comment by presidentbeef** [comment]
Please open a completely new issue.

"ruby_parser" and whitequark's "parser" are completely separate projects with similar functionality and unfortunately very similar names. The gemspec is essentially [here](https://github.com/seattlerb/ruby_parser/blob/master/Rakefile#L16).

Not sure about the `racc` error you are seeing.

FWIW the repro code can be reduced to

```ruby
a = b&.c
```

so it's something to do with assignment.

**Comment by gkop** [comment]
Thanks @presidentbeef for the info and help reducing the test case. Captured in #214 .

**Comment by zenspider** [comment]
Closing

**Comment by dsferreira** [comment]
```
a = (b&.c) 
```

is a workaround while this is still open in the wild. Just for anyone facing the same issue.
