### ISSUE TITLE
regexp interpolation with modifier results in strange sexpr

### ISSUE THREAD

**Issue by eqv** [seattlerb/ruby_parser#221]
`foo = /a#{b}c/m` parses to 
```
s(:lasgn, :foo, s(:dregx, "a", s(:evstr, s(:call, nil, :b)), s(:str, "c"), 4))
```
I think the 4 at the end is quite strange (the modifiers seem to map directly to bitmasks used). I think this is not according to the spirit of parsing sexpressions. something like s(:mod, "m") would seem more reasonable to me.

**Comment by zenspider** [comment]
It is what it is and works well enough. Making a backwards incompatible change for this doesn't work for me. Sorry.
