### ISSUE TITLE
Parse error on hash where value is return value of multi line if

### ISSUE THREAD

**Issue by trueb2** [seattlerb/ruby_parser#225]
Here is the error

> /usr/local/lib/ruby/2.1.0/racc/parser.rb:529:in `on_error' #<Racc::ParseError: /home/code/xyz/app/controllers/xyz_api/xyzs_controller.rb:7 :: parse error on value ":" (tCOLON)> for /home/code/xyz/app/controllers/xyz_api/xyzs_controller.rb
>   /usr/local/lib/ruby/2.1.0/racc/parser.rb:529:in`on_error'
>   /usr/local/bundle/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1165:in `on_error'
>   /usr/local/lib/ruby/2.1.0/racc/parser.rb:258:in`_racc_do_parse_c'
>   /usr/local/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'
>   /usr/local/bundle/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1077:in`block in process'
>   /usr/local/lib/ruby/2.1.0/timeout.rb:90:in `block in timeout'
>   /usr/local/lib/ruby/2.1.0/timeout.rb:33:in`block in catch'
>   /usr/local/lib/ruby/2.1.0/timeout.rb:33:in `catch'
>   /usr/local/lib/ruby/2.1.0/timeout.rb:33:in`catch'
>   /usr/local/lib/ruby/2.1.0/timeout.rb:105:in `timeout'
>   /usr/local/bundle/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1065:in`process'
>   /usr/local/bundle/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1408:in `block in process'
>   /usr/local/bundle/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1406:in`each'
>   /usr/local/bundle/gems/ruby_parser-3.8.2/lib/ruby_parser_extras.rb:1406:in `process'
>   /usr/local/bundle/gems/ruby_parser-3.8.2/bin/ruby_parse:48:in`block in <top (required)>'
>   /usr/local/bundle/gems/ruby_parser-3.8.2/bin/ruby_parse:29:in `each'
>   /usr/local/bundle/gems/ruby_parser-3.8.2/bin/ruby_parse:29:in`<top (required)>'
>   /usr/local/bundle/bin/ruby_parse:17:in `load'
>   /usr/local/bundle/bin/ruby_parse:17:in`<main>'
> done

The pseudo code that breaks this, but does just fine with `ruby -c` is

```
    def index
      render json: if guard1
                     MyActiveRecord.all
                   elsif guard2
                     MyActiveRecord.find(some_ids)
                   else
                     MyActiveRecord.find(some_other_ids)
                   end
    end
```

The line number that is supplied in the trace is totally off, like not even close. However, I did find the solution to get ruby_parser to parse everything.

```
    def index
      my_var = if guard1
                 MyActiveRecord.all
               elsif guard2
                 MyActiveRecord.find(some_ids)
               else
                 MyActiveRecord.find(some_other_ids)
               end
      render json: my_var
    end
```

**Comment by presidentbeef** [comment]
I believe this was fixed by https://github.com/seattlerb/ruby_parser/commit/41e3cbb7dbb59ba8c1e45fb637f6579381f33788

**Comment by zenspider** [comment]
Verified fixed. Closing.
