### ISSUE TITLE
Another segfault when running rubycritic

### ISSUE THREAD

**Issue by thedrow** [seattlerb/ruby_parser#235]
```
Running rubycritic.
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.5-compliant syntax, but you are running 2.2.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
running flay smells
..................................................................................................................
running flog smells
...............................................
running reek smells
..................*** Error in `ruby': free(): invalid size: 0x0000000003f58b30 ***
```
It only happened once and I cannot reproduce it. This is on CircleCI with Ubuntu 14.04.

**Comment by zenspider** [comment]
Can you upgrade off of 2.2.0 to a newer bug fix release?

**Comment by thedrow** [comment]
Currently we cannot do so since our application is running on Ruby 2.2.0.
We plan to upgrade to 2.4 as soon as we can.

**Comment by zenspider** [comment]
You can't upgrade to the latest in 2.2.x? There are security fixes in there. You should upgrade regardless of this bug.

**Comment by zenspider** [comment]
This is a bug in ruby, or a C extension you're using. It isn't in ruby_parser. I _highly_ recommend upgrading to the latest 2.2.x as 2.2.0 has known problems with stability.
