### ISSUE TITLE
Please support Ruby 2.4

### ISSUE THREAD

**Issue by dankohn** [seattlerb/ruby_parser#239]
[Fasterer](https://github.com/DamirSvrtan/fasterer) fails with the following error because ruby_parser doesn't yet support Ruby 2.4:
```bash
fasterer
/Users/dan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ruby_parser-3.8.3/lib/ruby_parser_extras.rb:1504:in `for_current_ruby': unrecognized RUBY_VERSION 2.4.0 (RuntimeError)
```
Could you please do so?

Cc @david-a-wheeler

**Comment by presidentbeef** [comment]
FWIW I think this illustrates why using `for_current_ruby` is not a great idea. ruby_parser will always be behind the latest Ruby version, but most (if not all) 2.4 syntax will parse just fine with ruby_parser's 2.3 parser.

**Comment by zenspider** [comment]
Should I add `latest`?

**Comment by presidentbeef** [comment]
Not sure it would be that helpful.

I think there are two scenarios:

1. Start with latest and fall back to earlier versions on failure (current default behavior)
2. Run with the parser meant for the specific version of Ruby in use (`for_current_ruby` behavior)

I think (2) is reasonable in theory but in practice you run into the issue above.

I think `latest` would only be useful when you really want (2) but you know you are running the latest Ruby.

**Comment by zenspider** [comment]
Well, 1 is worse than that, because it actually uses ALL parser versions in succession. Potentially horribly expensive.

What if `for_current_ruby` always fell back to the latest (w/ a warning if necessary)?

**Comment by presidentbeef** [comment]
From looking at the code, it still appears to me that older parsers are only used if newer ones fail. Of course if you need to parse 1.8-only code that's going to be rough.

`for_current_ruby` falling back with a warning makes sense to me.

**Comment by voxik** [comment]
#241 seems to be related ...

**Comment by rhymes** [comment]
any news?

**Comment by zenspider** [comment]
I've added both `RubyParser.latest` and made it so that `RubyParser.for_current_version` automatically falls back to the most recent when there is no clear match.

I've also added 2.4 support. Coming soon.
