### ISSUE TITLE
Ruby version 2.4.0 not yet supported?

### ISSUE THREAD

**Issue by rbatllet** [seattlerb/ruby_parser#246]
When I run my existing migrations, the following warning is displayed:

```
Error reading triggers in db/migrate/20160306143330_add_item_to_my_table.rb: unrecognized RUBY_VERSION 2.4.0
```

**Comment by presidentbeef** [comment]
See #239

**Comment by rbatllet** [comment]
I've just updated all the gems, but the error persists. Are you sure it has been fixed ?

**Comment by presidentbeef** [comment]
It's not released yet.

**Comment by rbatllet** [comment]
Ah!. 

My all migrations are `Ruby 2.3.x` compatible

**Comment by rbatllet** [comment]
I hope Ruby 2.4.1 will be supported soon as well

**Comment by zenspider** [comment]
Tentative 2.4 support went out in 3.9.0 on 4/13.
