### ISSUE TITLE
`self` target for `[]` calls reported as nil

### ISSUE THREAD

**Issue by presidentbeef** [seattlerb/ruby_parser#250]
Is this intentional?

```
2.3.1 :001 > require 'ruby_parser'
 => true 
2.3.1 :002 > RubyParser.new.parse "self[:x]"
 => s(:call, nil, :[], s(:lit, :x)) 
```

I would have expected

`s(:call, s(:self), :[], s(:lit, :x))`

**Comment by zenspider** [comment]
It's both. Probably a historical artifact going back to ParseTree. If you look at ruby2ruby you'll see where I `||= s(:self)`  in places. I'm happy to take a patch to make this more consistent.

**Comment by zenspider** [comment]
This is fixed. Release "soon" :P
