### ISSUE TITLE
Fork 1.8 and 1.9 parsers into ruby_parser_legacy gem

### ISSUE THREAD

**Issue by zenspider** [seattlerb/ruby_parser#251]
I don't think this will impact anyone but me (in a positive sense), but just in case I'm putting this out there.

**Comment by zenspider** [comment]
@presidentbeef @a_matsuda ... dunno who else to ping about this.

**Comment by amatsuda** [comment]
I don't think you need to create a new gem just for the legacy support.
Just set `required_ruby_version` in the gemspec to `'>= 2.0.0'` as you drop support for ruby 1.x in trunk, then make a new release (maybe a major update).
Future Ruby 1 users will stay on already released versions (maybe 3.x.y).

**Comment by zenspider** [comment]
> On Jun 17, 2017, at 04:42, Akira Matsuda <notifications@github.com> wrote:
> 
> I don't think you need to create a new gem just for the legacy support.
> Just set required_ruby_version in the gemspec to '>= 2.0.0' as you drop support for ruby 1.x in trunk, then make a new release (maybe a major update).
> Future Ruby 1 users will stay on already released versions (maybe 3.x.y).

This is forking off the 1.8 and 1.9 *parser*, not limiting to what runtime the parsers run on. Sorry for not being more clear.

**Comment by presidentbeef** [comment]
I don't think this is going to cause any problems. I'm assuming if you pull in the legacy gem and ruby_parser then it will be just like today.

**Comment by zenspider** [comment]
Turns out that this might be hard... lots of conditionals throughout the code. :(

**Comment by zenspider** [comment]
I would rather DROP support for 1.8 and 1.9. Fork them into their own gems and strip all conditionals dealing with them from the current version. I could see some way in which they can inject themselves into the VERSIONS in some way... but honestly? It will still probably take a lot of work and... What's the benefit? The amount of code out there that only parses under 1.8 or 1.9 is minuscule and it isn't unreasonable to update the code. We're talking about dropping support for parsing expressions like `case obj; when x: ...`... things that weren't actually popular to begin with and haven't been supported for ages.

**Comment by presidentbeef** [comment]
That's okay with me... (I'll probably still re-implement the fall-back behavior.)

**Comment by zenspider** [comment]
I just violently ripped this out:

```
9990 % git diff | grep -c ^-
4371
9991 % git diff | grep -c ^\\+
43
```

That's a clear win for me. (Inflated for file deletions, but still)

I can push up this fork separately so you can poke at it.

**Comment by zenspider** [comment]
https://github.com/zenspider/ruby_parser/tree/drop_legacy

**Comment by zenspider** [comment]
This runs clean AFTER sexp_processor's pt_testcase.rb doesn't generate 1.8 or 1.9 tests. I hacked that out by hand. It's a bit messy, but that's what happens when you depend on tests.

**Comment by presidentbeef** [comment]
Checking it out now and will report back.

**Comment by presidentbeef** [comment]
Hm, yeah I'll have to support falling back on the legacy gem. But I don't mind.

**Comment by zenspider** [comment]
Hey look! I did this!
