### ISSUE TITLE
usage of environment variable DEBUG

### ISSUE THREAD

**Issue by mmoll** [seattlerb/ruby_parser#253]
in 47cf88ed6 the following is introduced:
```ruby
$DEBUG = true if ENV["DEBUG"] 
```
However, that's bit broad and if this really should be there, it should rather use a variable like `RUBY_PARSER_DEBUG`.

**Comment by zenspider** [comment]
Not sure I understand what your concern is. `$DEBUG` is a standard ruby global.

**Comment by mmoll** [comment]
Shouldn't it be `$DEBUG` instead of `ENV["DEBUG"] ` then?

**Comment by mmoll** [comment]
@zenspider any comment here?
