### ISSUE TITLE
parse error on value ":" (tCOLON)

### ISSUE THREAD

**Issue by suryateja619** [seattlerb/ruby_parser#256]
ruby_parser 3.8.2 & 3.10.1

I get an error when using the following code.

```enum view_level: [ :associates, :clients, :not_tracked ]```

`parse error on value ":" (tCOLON)`

It's a valid Rails [syntax](http://api.rubyonrails.org/v5.1/classes/ActiveRecord/Enum.html) for the enum.

I have no syntax errors as well. 

``` 
ruby -c file.rb
Syntax Ok
```

**Comment by presidentbeef** [comment]
@suryateja619 try updating RubyParser to the latest.

```
$ irb
2.4.1 :001 > require 'ruby_parser'
 => true
2.4.1 :002 > RubyParserStuff::VERSION
 => "3.10.1"
2.4.1 :003 > RubyParser.new.parse "enum view_level: [ :associates, :clients, :not_tracked ]"
 => s(:call, nil, :enum, s(:hash, s(:lit, :view_level), s(:array, s(:lit, :associates), s(:lit, :clients), s(:lit, :not_tracked))))
```

**Comment by suryateja619** [comment]
@presidentbeef Tried updating to the latest version of RubyParser. It didn't help. It was causing the errors when we run brakeman `bundle exec brakeman`

It gave the similar output for RubyParser version 3.8.2 and the latest one.

```irb(main):001:0> require 'ruby_parser'
=> true
irb(main):002:0> RubyParserStuff::VERSION
=> "3.8.2"
irb(main):003:0> RubyParser.new.parse "enum view_level: [ :associates, :clients, :not_tracked ]"
=> s(:call, nil, :enum, s(:hash, s(:lit, :view_level), s(:array, s(:lit, :associates), s(:lit, :clients), s(:lit, :not_tracked))))```

**Comment by presidentbeef** [comment]
@suryateja619 what version of Brakeman are you using? Try updating to the latest. Brakeman vendors RubyParser, so it does not matter which version of RubyParser you have installed.

**Comment by suryateja619** [comment]
@presidentbeef I'm using the latest version 4.0.1.

**Comment by presidentbeef** [comment]
@suryateja619 Sorry, I can't reproduce that error. Can you open an issue over at https://github.com/presidentbeef/brakeman since this doesn't look like a RubyParser problem?

**Comment by suryateja619** [comment]
@presidentbeef Opened a issue in brakeman repo.

**Comment by zenspider** [comment]
I can't reproduce either. I can show @presidentbeef's results in irb as well.

Should this be closed?

**Comment by zenspider** [comment]
Yeah. I think this should be closed. Please poke at me if you don't agree.
