### ISSUE TITLE
Ruby 2.5 support

### ISSUE THREAD

**Issue by voxik** [seattlerb/ruby_parser#257]
Could you please add support for Ruby 2.5.x? Thx.

**Comment by zenspider** [comment]
done! thanks!

**Comment by voxik** [comment]
Thank you!

**Comment by DamirSvrtan** [comment]
Hey @zenspider, is there any chance to get a new release of the gem? The latest version seems to be released in [mid 2017](https://rubygems.org/gems/ruby_parser) without the support of Ruby 2.

My lib [fasterer](https://github.com/DamirSvrtan/fasterer) is heavily depending on the ruby parser and people have problems with the lack of Ruby 2.5. support: https://github.com/DamirSvrtan/fasterer/issues/46

Thanks!
