### ISSUE TITLE
Self-signed code signing certificate has expired

### ISSUE THREAD

**Issue by koenrh** [seattlerb/ruby_parser#259]
The certificate that is used by users to verify the signature of signed gems has expired. 

## Steps to reproduce

1. Get the developer's self-signed code signing certificate, and save it as `zenspider.pem`. I pulled it from this gem package's metadata. The one that is available at `https://www.zenspider.com/~ryan/gem-public_cert.pem` has expired a few years ago.
2. Add the developer's certificate to your local trust store: `gem cert --add zenspider.pem`.
2. Attempt to install a version of the gem that is signed: `gem install ruby_parser -v 3.10.1 --trust-policy HighSecurity`.
3. Note the error:
```
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=ryand-ruby/DC=zenspider/DC=com not valid after 2017-09-26 01:57:35 UTC
```
5. Alternatively, view the certificate's contents (using `openssl x509 -in zenspider.pem -noout -text`), and note the expiration date (Not After).

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: CN=ryand-ruby, DC=zenspider, DC=com
        Validity
            Not Before: Sep 26 01:57:35 2016 GMT
            Not After : Sep 26 01:57:35 2017 GMT
        Subject: CN=ryand-ruby, DC=zenspider, DC=com

...
```

Here's a copy of the (now expired) code signing certificate:

```
-----BEGIN CERTIFICATE-----
MIIDijCCAnKgAwIBAgIBATANBgkqhkiG9w0BAQUFADBFMRMwEQYDVQQDDApyeWFu
ZC1ydWJ5MRkwFwYKCZImiZPyLGQBGRYJemVuc3BpZGVyMRMwEQYKCZImiZPyLGQB
GRYDY29tMB4XDTE2MDkyNjAxNTczNVoXDTE3MDkyNjAxNTczNVowRTETMBEGA1UE
AwwKcnlhbmQtcnVieTEZMBcGCgmSJomT8ixkARkWCXplbnNwaWRlcjETMBEGCgmS
JomT8ixkARkWA2NvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALda
b9DCgK+627gPJkB6XfjZ1itoOQvpqH1EXScSaba9/S2VF22VYQbXU1xQXL/WzCkx
taCPaLmfYIaFcHHCSY4hYDJijRQkLxPeB3xbOfzfLoBDbjvx5JxgJxUjmGa7xhcT
oOvjtt5P8+GSK9zLzxQP0gVLS/D0FmoE44XuDr3iQkVS2ujU5zZL84mMNqNB1znh
GiadM9GHRaDiaxuX0cIUBj19T01mVE2iymf9I6bEsiayK/n6QujtyCbTWsAS9Rqt
qhtV7HJxNKuPj/JFH0D2cswvzznE/a5FOYO68g+YCuFi5L8wZuuM8zzdwjrWHqSV
gBEfoTEGr7Zii72cx+sCAwEAAaOBhDCBgTAJBgNVHRMEAjAAMAsGA1UdDwQEAwIE
sDAdBgNVHQ4EFgQUR8V72Z3+v+2P9abCnL4wjx32T+EwIwYDVR0RBBwwGoEYcnlh
bmQtcnVieUB6ZW5zcGlkZXIuY29tMCMGA1UdEgQcMBqBGHJ5YW5kLXJ1YnlAemVu
c3BpZGVyLmNvbTANBgkqhkiG9w0BAQUFAAOCAQEAIGzgp0aZ2W9+v96ujmBcQHoC
buy0iU68MVj2VlxMyfr1KPZIh1OyhU4UO4zrkREcH8ML70v9cYHNvOd9oynRHnvC
l2tj/fD3YJ0AEkJxGrYwRWQmvMfC4bJ02bC1+rVOUIXXKp3+cUmiN4sTniof8VFo
bo/YYP4c7erpERa+9hrqygg6WQbJlk2YRlH3JXPFjmu869i2dcbR5ZLOAeEy+axH
E4oJcnPkJAr0rw504JGtlZtONZQblwmRJOIdXzolaE3NRGUzGVOUSptZppAKiavY
fO6tdKQc/5RfA8oQEkg8hrxA5PQSz4TOFJGLpFvIapEk6tMruQ0bHgkhr9auXg==
-----END CERTIFICATE-----
```

**Comment by zenspider** [comment]
Preface: I'm not a security guy.

OK. I've done two things to help mitigate this:

1. I've released on 2/14 which automatically refreshes my cert now (whew—it was such a PITA) whenever you build and have signing set up.
2. I've deleted the old public cert and hard linked it to the actual in-use public key file. (and rsync'd to my website)

I haven't looked at the signing code in rubygems in a while, so I don't know if they update in place or if they roll a new file to that location. If the latter, then the second step won't actually help in the long term. I could set up a cron job or something to copy it periodically if necessary.

Think that covers it?
