### ISSUE TITLE
ruby_parser's executable "ruby_parse" conflicts with ~/.rbenv/versions/2.4.3/bin/ruby_parse

### ISSUE THREAD

**Issue by UtamaruMonster** [seattlerb/ruby_parser#263]
Good day.

Wanted to install ```ruby_parser```. This is what i've got.

```ruby_parser's executable "ruby_parse" conflicts with ~/.rbenv/versions/2.4.3/bin/ruby_parse```

Is this normal?

Thank you.

**Comment by zenspider** [comment]
My guess is if you look at the contents of `~/.rbenv/versions/2.4.3/bin/ruby_parse` that you'll see it is pointing to another installation of the gem.

**Comment by zenspider** [comment]
Anything?

**Comment by zenspider** [comment]
No response. Closing.
