### ISSUE TITLE
Could the latest master be released?

### ISSUE THREAD

**Issue by Jack12816** [seattlerb/ruby_parser#268]
Thanks for this great gem! 

But due to missing ruby 2.5 support on the latest released version many people have [trouble with brakeman](https://github.com/presidentbeef/brakeman/issues/1173), etc. Could you just publish a release? @zenspider :)

**Comment by benhutton** [comment]
alternatively, is there some secret to running this gem directly off of github? Or is a new release essential?

**Comment by Jack12816** [comment]
@benhutton I forked it and made it compatible for now until the release was done. In combination with brakeman it looks like this:

```ruby
  # Until we get a new release. See: http://bit.ly/2PDt3LI
  # @TODO: Remove as soon as possible.
  gem 'ruby_parser',
      github: 'Jack12816/ruby_parser',
      branch: 'master',
      require: false
  # Brakeman is an open source static analysis tool which checks Ruby on Rails
  # applications for security vulnerabilities
  # gem 'brakeman', require: false
  # @TODO: Remove as soon as possible.
  gem 'brakeman',
      github: 'presidentbeef/brakeman',
      branch: 'v4.3.1',
      require: false   
```

Brakeman bundles the ruby_parser gem inside its released versions, so we need to use it off of Github, too.
