### ISSUE TITLE
Ruby 2.6 support

### ISSUE THREAD

**Issue by DamirSvrtan** [seattlerb/ruby_parser#279]
Hi there! First of all, thank you for your hard work!

I'm the maintainer of the Fasterer project (https://github.com/DamirSvrtan/fasterer) and it seems that users using it on Ruby 2.6 (https://github.com/DamirSvrtan/fasterer/issues/55) are getting warnings such as:

`NOTE: RubyParser::V26 undefined, using RubyParser::V25`

As much as I see, there are no errors so far.

The build output for Ruby 2.6 looks like this: https://travis-ci.org/DamirSvrtan/fasterer/jobs/482727262#L537

Do you know when this will be resolved? 

Thank you!

**Comment by zenspider** [comment]
2.6 support added. Coming soon.
