### ISSUE TITLE
Parser fails with method.method.method(symbol: Constant::CONSTANT)

### ISSUE THREAD

**Issue by envygeeks** [seattlerb/ruby_parser#281]
```
Parser process id: 12
codeclimate-parser socket not present
waiting 1s...
I, [2019-02-11T22:12:30.662677 #1]  INFO -- : Skipping file ./app/lib/private_factory.rb due to exception (Racc::ParseError): ./app/lib/private.rb:12 :: parse error on value ":" (tCOLON)
/usr/lib/ruby/2.3.0/racc/parser.rb:528:in `on_error'
/var/lib/gems/2.3.0/gems/ruby_parser-3.11.0/lib/ruby_parser_extras.rb:1175:in `on_error'
/usr/lib/ruby/2.3.0/racc/parser.rb:259:in `_racc_do_parse_c'
```

I can provide more details if needed! Though I'm not quite sure if this is an RACC problem.

**Comment by presidentbeef** [comment]
@envygeeks Can you provide a small, anonymized bit of code to reproduce the problem? It's often not where it may seem. I usually do a binary search by deleting code until I get a minimal example.

**Comment by envygeeks** [comment]
@presidentbeef Indeed, when I'm at my laptop in the morning I will get one for you.

**Comment by envygeeks** [comment]
I've not forgot about this, I'll be trying to get the example this week I just ended up super busy.

**Comment by zenspider** [comment]
It doesn't need to be anonymized. Often there isn't enough context to matter and the effort isn't worth it. If you really don't care, throw me a gist of the whole thing. I'm pretty good at extracting quickly.

**Comment by cblackburn-ajla** [comment]
Following up, here's what it is currently choking on:

```
# wonky_user.rb
class WonkyUser
  USER_CONTACT_SCHEMA = {
    contact_info_phones: [
      { label: 'Phone', precedence: 1 }
    ],
    contact_info_emails: [{ label: 'Email', precedence: 1 }],
    contact_info_addresses: [{ label: 'Address', precedence: 1 }]
  }.freeze
end

# wonky_account_factory.rb
module WonkyAccountFactory
  class << self
    def wonky_user(opts = {})
      wonky_user = WonkyUser.new(opts)
      wonky_user.user ||= User.new
      wonky_user.user.approval_status ||= :pending_approval
->    wonky_user.user.construct_contact(contact_schema: WonkyUser::USER_CONTACT_SCHEMA)
      wonky_user
    end
  end
end
```

We are excluding the file from code climate for now.  Let us know if we can provide any more info.

**Comment by zenspider** [comment]
@envygeeks / @cblackburn-ajla : to be pedantically clear, you do **NOT** mean to include the `->` in there as syntax... just pointing out the line it is choking on?

This snippet parses fine (without the `->`) in all versions going back to at least 2016 (3.8.0 up to last week's release). 

I suspect you need to include some more to properly reproduce? CodeClimate should be fairly up to date wrt ruby_parser versions. I worked on their platform around this time last year and it was up to date.

If I'm misunderstanding something, please advise.

**Comment by envygeeks** [comment]
@zenspider indeed that is correct, the `->` is should just be a pointer to the problem area. I'll get hold of @cblackburn-ajla this morning and see if there is anything that needs to be updated!

**Comment by zenspider** [comment]
I'm going to close this. Please open a new ticket if you find any reproducible test case.
