### ISSUE TITLE
Heredocs with line continuations lower line numbers for later lines

### ISSUE THREAD

**Issue by mvz** [seattlerb/ruby_parser#292]
```ruby
[38] pry(main)> str = "<<TXT\nfoo\\\nbar\nTXT\nfoo"; puts str
<<TXT
foo\
bar
TXT
foo
=> nil
[39] pry(main)> RubyParser.for_current_ruby.parse(str)
=> s(:block, s(:str, "foobar\n").line(1), s(:call, nil, :foo).line(4)).line(1)
```

The call to `foo` is on line 5, but `s(:call, nil, :foo)` has line number 4.

**Comment by zenspider** [comment]
Heredocs and line numbers are just a complete clusterfuck. Unfortunately, they're not going to get fixed until I completely rewrite all string/heredoc parsing entirely. It's just bad. Real bad.

I _think_ I already have a skipped test or two that covers this issue. If not, then can you send me a PR with one for this case?

**Comment by zenspider** [comment]
Aaaand I completely rewrote it. This is fixed. Release coming soonish.
