### ISSUE TITLE
What are the supported Ruby version on the ruby_parser?

### ISSUE THREAD

**Issue by DamirSvrtan** [seattlerb/ruby_parser#298]
Hi! 👋 I was wondering what were the supported versions of Ruby for the ruby_parser project?

The [fasterer](https://github.com/DamirSvrtan/fasterer) project depends on the Ruby parser and the travis CI build has been failing on ruby versions 1.9.3 and 2.0.0 since the latest version of the ruby parser gem 3.14.0.

I saw in the history file that there is some drop of support for 1.8.x and 1.9.x., but i was wondering if there's somewhere where I could find out explicitly which versions are supported?

To be clear, I have no issues dropping support for those older versions. Btw the errors can be seen [here](https://travis-ci.org/DamirSvrtan/fasterer/jobs/593820494).

**Comment by zenspider** [comment]
I dropped 1.8 and 1.9 for _parsing_ and put them in the `ruby_parser-legacy` gem. You can add that dependency, require it, and they should work again.

As far as runtime goes, yeah. I've only been testing against ruby 2.4 and up (the supported ruby lines) but recently that caused problems with my minitest gem and had to go back down to 2.2. For `to_h` errors you'd definitely need a ruby 2.1 and higher. I'll add metadata to the gem to be more explicit.

**Comment by DamirSvrtan** [comment]
Thanks @zenspider, adding metadata would be great! Thanks for the detailed explanation! Lemme know when it's done or I can open a PR as well - whatever's easier for you!

**Comment by zenspider** [comment]
All done. Just not released yet.

**Comment by zenspider** [comment]
Released

**Comment by DamirSvrtan** [comment]
Thanks @zenspider!
