### ISSUE TITLE
Pattern matching / Ruby 2.7 support

### ISSUE THREAD

**Issue by dansteele** [seattlerb/ruby_parser#308]
Hey! Found my way here from Brakeman.
Thanks for all your work on this!
I'm pretty certain you're already aware (and are working on 2.7 support), but thought I'd let you know just in case.

```ruby
      self.class.stringify_and_demark_keys_for(hash) in {
        hash: hash,
        stripe_keys: stripe_keys,
        local_keys: local_keys
      }
```

Ruby 2.7 pattern matching in this case leads to `parse error on value ["in", 33] (kIN)`

**Comment by zenspider** [comment]
Absolutely true. I haven't done any 2.7 work yet.

**Comment by dansteele** [comment]
Hey @zenspider, do you have a rough ETA for this? Asking purely for whether we should adjust some of the code internally so that Brakeman is happy again :innocent:

**Comment by zenspider** [comment]
No ETA. I've stubbed out 2.7 (need to do 3.0 now... ugh). The skeleton is all there and it structurally matches MRI's 2.7 grammar as close as possible (IIRC)... but I didn't implement any of the new constructs.

Not sure if I can muster it at this point.

**Comment by presidentbeef** [comment]
@zenspider can you clarify? Is all the Racc / lexing stuff done, but it "just" needs the AST implementation? I could probably handle the rest if so.

**Comment by presidentbeef** [comment]
Does it make sense to skip Ruby 2.7 pattern matching syntax and go straight to 3.0? 🤔 Especially since it was "experimental" in 2.7? I _think_ the differences are minor.

**Comment by zenspider** [comment]
> On Feb 12, 2021, at 20:30, Justin Collins <notifications@github.com> wrote:
> 
> 
> Does it make sense to skip Ruby 2.7 pattern matching syntax and go straight to 3.0? 🤔 Especially since it was "experimental" in 2.7? I think the differences are minor.

Bleh... I don't know... Catching up with 2.7 seems like the right thing to do... to make sure the bases are covered before transitioning to a 3.0 skeleton. But I'm open on this one.

**Comment by zenspider** [comment]
I did a bunch of work to catch up to 2.7... but fuck pattern matching is daunting. Without failing tests, I'm not sure how much of a fuck I can muster.

**Comment by presidentbeef** [comment]
I can provide failing tests!

**Comment by zenspider** [comment]
This is all done. Release coming soonish.
