### ISSUE TITLE
Parsing comments

### ISSUE THREAD

**Issue by jrperron88** [seattlerb/ruby_parser#310]
Has there been any thought into being able to keep comments in the parsing? Working on a project now that this is almost perfect for, but we need to preserve comments. From the documentation it sounds like you are supposed to support class/module/def/defn comments, but That hasn't worked for me, or any comments.

**Comment by zenspider** [comment]
I don't think it'll ever be good at keeping _all_ comments... but it definitely does (did?) work for class/module/defs/defn... Can you show me something not working for you?

**Comment by zenspider** [comment]
no response... closing
