### ISSUE TITLE
RubyParser::V30 undefined

### ISSUE THREAD

**Issue by mepatterson** [seattlerb/ruby_parser#319]
Seeing this warning a bunch: `NOTE: RubyParser::V30 undefined, using RubyParser::V27`

Anything I can change to squelch this? Doesn't seem to be causing issues so much as just spamming my logs at the moment...

**Comment by zenspider** [comment]
If you're invoking, you can switch to using the specific version that works for you... If you're not, wait for a release that has 3.0 stubbed out. (or run ruby 2.7? :P)

**Comment by zenspider** [comment]
fixed a while ago
