### ISSUE TITLE
Ruby 3.0 "endless" methods are not parsed

### ISSUE THREAD

**Issue by mildred** [seattlerb/ruby_parser#320]
https://rubyreferences.github.io/rubychanges/3.0.html#endless-method-definition

The minimal source below fails to parse:

```rb
def a = :a
```

**Comment by zenspider** [comment]
confirmed

**Comment by davidcarlin-ap** [comment]
This is a bit of a problem for me. Do you have any idea of when this will be fixed? Thanks

**Comment by davidcarlin-ap** [comment]
It looks like this was fixed in this commit https://github.com/seattlerb/ruby_parser/commit/b877e46d5ac5b2fcd94e0d7ff118bbdbd6e34e04
Can we get a new release for this please ? ❤️

**Comment by presidentbeef** [comment]
Yes, I'm planning a small bug fix release in the next couple weeks. I can update ruby_parser then.
