### ISSUE TITLE
Ruby 3.0 argument forwarding does not parse

### ISSUE THREAD

**Issue by mildred** [seattlerb/ruby_parser#321]
https://rubyreferences.github.io/rubychanges/3.0.html#arguments-forwarding--supports-leading-arguments

The following minimal ruby example do not parse:

```rb
def a(...)
  b(...)
end
```

**Comment by danleyden** [comment]
I believe this is a duplicate of #311

**Comment by zenspider** [comment]
Dupe and fixed
