### ISSUE TITLE
Parenthesisless method calls in endless method definitions (Ruby-3.1 support)

### ISSUE THREAD

**Issue by ojab** [seattlerb/ruby_parser#328]
https://rubyreferences.github.io/rubychanges/3.1.html#inside-endless-method-definitions-method-calls-without-parenthesis-are-allowed

```ruby
def log(msg) = puts "#{Time.now}: #{msg}"
```
should be allowed

**Comment by zenspider** [comment]
This has been addressed in the latest release.
