### ISSUE TITLE
Parentheses can be omitted in one-line pattern matching (Ruby-3.1 support)

### ISSUE THREAD

**Issue by ojab** [seattlerb/ruby_parser#329]
https://rubyreferences.github.io/rubychanges/3.1.html#parentheses-can-be-omitted-in-one-line-pattern-matching
```ruby
[0, 1] => _, x

{y: 2} => y:

if {language: 'Ruby', version: '3.1'} in version: ('3.0'..)
  puts "Pattern-matching is cool"
end
```
should be parsed correctly

**Comment by zenspider** [comment]
This has been addressed in the latest release.
