### ISSUE TITLE
Anonymous argument passing (Ruby-3.2 support)

### ISSUE THREAD

**Issue by agrobbin** [seattlerb/ruby_parser#338]
I tried to mimic the issues created for the new features introduced in Ruby 3.1, hopefully this is sufficient, but if not please let me know!

https://rubyreferences.github.io/rubychanges/3.2.html#anonymous-arguments-passing-improvements

```ruby
def foo(*, **)
  bar(*, **)
end
```

This should be parsed as valid Ruby in 3.2, but at the moment is raising a parsing error.

**Comment by zenspider** [comment]
this is fixed and will go out in the next release. Thanks for the report!

**Comment by agrobbin** [comment]
Thanks for the quick fix, @zenspider!
